### ISSUE TITLE
Can't specify label  parameter 

### ISSUE THREAD

**Issue by joseamt** [joonhocho/vcard-generator#3]
while creating multiple URL's, cant specify the label parameter. when we specify it, will not reflect in the response.

        const vcardContent = vcard.generate({

            name: {
                familyName: 'test',
            },
            emails: [{
                type: 'work',
                text: 'info@test.com',
            }],
            phones: [{
                type: 'SMS',
                text: '+1408338',
            }],
            urls: [{
                type:'whatsapp',
               label:'Whatsapp'
                uri: 'https://api.whatsapp.com/send?phone=+4915',
            }]

        });

getting without label responce

BEGIN:VCARD
VERSION:4.0
N:test;;;;
EMAIL;TYPE=work:info@test.com
TEL;TYPE=SMS:+1408338
URL;TYPE=whatsapp:https://api.whatsapp.com/send?phone=+4915
END:VCARD

**Comment by joonhocho** [comment]
@joseamt https://github.com/joonhocho/vcard-generator/blob/master/src/URL.js
You cannot specify both type and label at the same time.
